# Generated by Django 4.2.11 on 2024-04-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
