# Generated by Django 4.2.11 on 2024-04-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
    ]
